# https://prometheus.io/docs/prometheus/latest/getting_started/
global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'backend-application'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
#        - alertmanger:9093

rule_files:

scrape_configs:
  - job_name: 'spring-actuator'
    scrape_interval: 5s
    metrics_path: /monitoring/actuator/prometheus
    basic_auth:
      username: wonjjong
      password: 1234
    static_configs:
      - targets: ["host.docker.internal:9091"] # actuator port
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']


